spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activi_test?seUnicode=true;characterEncoding=UTF-8 
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
spring:
  profiles:
    active: dev
